# Site settings
title: Myungkwan's Blog
email: myungkwan127@koreatech.ac.kr
description: > # this means to ignore newlines until "baseurl:"
 this is myblog my name is myungkwan oh and i'm student
 my university is koreatech and i'm junior
 haha;
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  myungkwan

# Build settings
markdown: kramdown
